<?php

namespace App\Admin\Actions\Post;

use Encore\Admin\Actions\RowAction;
use Illuminate\Database\Eloquent\Model;

class Replicate extends RowAction
{
    public $name = '课程管理';

    public function handle(Model $model)
    {
        // $model ...
        // 这里调用模型的`replicate`方法复制数据，再调用`save`方法保存
//        $model->replicate()->save();

//        redirect('/admin/score');
//        return '/admin/score';
        return $this->response()->success('Success message.')->refresh();
    }

    public function href()
    {
        parent::href(); // TODO: Change the autogenerated stub

        return '/admin/scores';
    }
//    public function form()
//    {
//        $type = [
//            1 => '广告',
//            2 => '违法',
//            3 => '钓鱼',
//        ];
//
//        $this->checkbox('type', '课程')->options($type);
//        $this->textarea('memo', '备注')->rules('required');
//    }

}
